name: E2E Test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Set up Elixir
          uses: erlef/setup-beam@v1
          with:
            elixir-version: 1.16.0
            otp-version: 26.2

        - name: Install Dependencies
          run: mix deps.get

        - name: Run E2E test
          run: mix test test/escheduler_test.exs